name: Homebrew deploy
on:
  workflow_dispatch:
    inputs:
      api_url:
        required: true
        description: "API URL"
      auth_proxy:
        required: true
        description: "AUTH Proxy"
      ref:
        required: true
        description: "Ref"
      tag:
        required: true
        description: "Tag"
  repository_dispatch:
    types: [homebrew-deploy]
env:
  KSAPI_URL: ${{ inputs.api_url || github.event.client_payload.url }}
  AUTH_PROXY: ${{ inputs.auth_proxy || github.event.client_payload.auth_proxy }}
  REF: ${{ inputs.ref || github.event.client_payload.ref }}
  TAG: ${{ inputs.tag || github.event.client_payload.tag }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  HOMEBREW_OPT: /usr/local/opt
jobs:
  homebrew-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Load Secrets
        uses: wearedevx/keystone-action@main
        id: load_secrets
        with:
          keystone_slot_1: ${{ secrets.KEYSTONE_PROD_SLOT_1 }}
          keystone_slot_2: ${{ secrets.KEYSTONE_PROD_SLOT_2 }}
          keystone_slot_3: ${{ secrets.KEYSTONE_PROD_SLOT_3 }}
          keystone_slot_4: ${{ secrets.KEYSTONE_PROD_SLOT_4 }}
          keystone_slot_5: ${{ secrets.KEYSTONE_PROD_SLOT_5 }}
      - name: Run Template
        env:
          BRANCH: ${{ env.TAG }}
          #
          KSAPI_URL: ${{ env.KSAPI_URL }}
          AUTH_PROXY: ${{ env.AUTH_PROXY }}
          #
          VERSION: ${{ env.TAG }}
          GITHUB_CLIENT_ID: ${{ env.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ env.GITHUB_CLIENT_SECRET }}
          GITLAB_CLIENT_ID: ${{ env.GITLAB_CLIENT_ID }}
          GITLAB_CLIENT_SECRET: ${{ env.GITLAB_CLIENT_SECRET }}
        run: ./run_release.sh
      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          branch: master
          default_author: github_actions
          message: release ${{ env.TAG }}
  bottling:
    needs: homebrew-deploy
    # strategy:
    #   matrix:
    # os:
    #   - macos-10.15
    #   - macos-11
    #   - macos-12
    runs-on: macos-11
    # runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Install as bottle
        run: |-
          brew test-bot --tap wearedevx/homebrew-keystone wearedevx/keystone/keystone

          gh release create -F - -t ${{env.TAG}} ${{env.TAG}} 
          rename 's/--/-/g' *.tar.gz

          gh release upload **.tar.gz
          gh release upload **.json"
  deploy:
    runs-on: macos-latest
    needs: [bottling]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Publish the bottles
        run: |-
          gh release download --clobber ${{env.TAG}}

          echo 'echo "\n\n[ci skip]" >> "$1"' > .git/hooks/commit-msg; chmod +x .git/hooks/commit-msg
          if ls *.{json,tar.gz}; then
            brew test-bot --tap wearedevx/homebrew-keystone wearedevx/keystone/keystone --git-name "CI" --git-email "ci@wearedevx.com" --publish;
          else
            echo "===> No bottles found to publish";
          if;
